name: Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          project: paf-mvp-frontend
          start: npm run start --prefix paf-mvp-frontend
      - name: Unit tests
        run: |
          npm run test
          npm run test --prefix paf-mvp-frontend
